version: '3.7'

services:
  service:
    image: jankostrzewa/service
    build:
      context: ../Service
      dockerfile: Dockerfile
    ports:
       - "8000:80"

  frontend_angular:
    image: jankostrzewa/frontend_angular
    build:
      context: ../Frontend_Angular
      dockerfile: Dockerfile
    ports:
       - "8001:80"

  frontend_react:
    image: jankostrzewa/frontend_react
    build:
      context: ../Frontend_React
      dockerfile: Dockerfile
    ports:
       - "8002:80"

  frontend_javascript:
    image: jankostrzewa/frontend_javascript
    build:
      context: ../Frontend_Javascript
      dockerfile: Dockerfile
    ports:
       - "8003:80"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports: 
      - "8004:27017"